[package]
name = "tasinput-ui"
version = "0.1.0"
edition = "2021"

[dependencies]

m64prs-sys = { workspace = true }

glib = { version = "*", features = ["log"] }
gio = { version = "*" }
gdk = { version = "*", package = "gdk4", features = ["v4_14"] }
gtk = { version = "0.9.3", package = "gtk4", features = ["v4_14", "blueprint"] }
bitflags = "2.6.0"
