use sdl2::keyboard::{Keycode, Mod};

pub fn into_sdl_keycode(key: gdk::Key) -> Option<Keycode> {
    match key {
        gdk::Key::BackSpace => Some(Keycode::BACKSPACE),
        gdk::Key::Tab => Some(Keycode::TAB),
        gdk::Key::Return => Some(Keycode::RETURN),
        gdk::Key::Escape => Some(Keycode::ESCAPE),
        gdk::Key::space => Some(Keycode::SPACE),
        gdk::Key::exclam => Some(Keycode::EXCLAIM),
        gdk::Key::quotedbl => Some(Keycode::QUOTEDBL),
        gdk::Key::numbersign => Some(Keycode::HASH),
        gdk::Key::dollar => Some(Keycode::DOLLAR),
        gdk::Key::percent => Some(Keycode::PERCENT),
        gdk::Key::ampersand => Some(Keycode::AMPERSAND),
        gdk::Key::apostrophe => Some(Keycode::QUOTE),
        gdk::Key::parenleft => Some(Keycode::LEFTPAREN),
        gdk::Key::parenright => Some(Keycode::RIGHTPAREN),
        gdk::Key::asterisk => Some(Keycode::ASTERISK),
        gdk::Key::plus => Some(Keycode::PLUS),
        gdk::Key::comma => Some(Keycode::COMMA),
        gdk::Key::minus => Some(Keycode::MINUS),
        gdk::Key::period => Some(Keycode::PERIOD),
        gdk::Key::slash => Some(Keycode::SLASH),
        gdk::Key::_0 => Some(Keycode::NUM_0),
        gdk::Key::_1 => Some(Keycode::NUM_1),
        gdk::Key::_2 => Some(Keycode::NUM_2),
        gdk::Key::_3 => Some(Keycode::NUM_3),
        gdk::Key::_4 => Some(Keycode::NUM_4),
        gdk::Key::_5 => Some(Keycode::NUM_5),
        gdk::Key::_6 => Some(Keycode::NUM_6),
        gdk::Key::_7 => Some(Keycode::NUM_7),
        gdk::Key::_8 => Some(Keycode::NUM_8),
        gdk::Key::_9 => Some(Keycode::NUM_9),
        gdk::Key::colon => Some(Keycode::COLON),
        gdk::Key::semicolon => Some(Keycode::SEMICOLON),
        gdk::Key::less => Some(Keycode::LESS),
        gdk::Key::equal => Some(Keycode::EQUALS),
        gdk::Key::greater => Some(Keycode::GREATER),
        gdk::Key::question => Some(Keycode::QUESTION),
        gdk::Key::at => Some(Keycode::AT),
        gdk::Key::bracketleft => Some(Keycode::LEFTBRACKET),
        gdk::Key::backslash => Some(Keycode::BACKSLASH),
        gdk::Key::bracketright => Some(Keycode::RIGHTBRACKET),
        gdk::Key::caret => Some(Keycode::CARET),
        gdk::Key::underscore => Some(Keycode::UNDERSCORE),
        gdk::Key::grave => Some(Keycode::BACKQUOTE),
        gdk::Key::A => Some(Keycode::A),
        gdk::Key::B => Some(Keycode::B),
        gdk::Key::C => Some(Keycode::C),
        gdk::Key::D => Some(Keycode::D),
        gdk::Key::E => Some(Keycode::E),
        gdk::Key::F => Some(Keycode::F),
        gdk::Key::G => Some(Keycode::G),
        gdk::Key::H => Some(Keycode::H),
        gdk::Key::I => Some(Keycode::I),
        gdk::Key::J => Some(Keycode::J),
        gdk::Key::K => Some(Keycode::K),
        gdk::Key::L => Some(Keycode::L),
        gdk::Key::M => Some(Keycode::M),
        gdk::Key::N => Some(Keycode::N),
        gdk::Key::O => Some(Keycode::O),
        gdk::Key::P => Some(Keycode::P),
        gdk::Key::Q => Some(Keycode::Q),
        gdk::Key::R => Some(Keycode::R),
        gdk::Key::S => Some(Keycode::S),
        gdk::Key::T => Some(Keycode::T),
        gdk::Key::U => Some(Keycode::U),
        gdk::Key::V => Some(Keycode::V),
        gdk::Key::W => Some(Keycode::W),
        gdk::Key::X => Some(Keycode::X),
        gdk::Key::Y => Some(Keycode::Y),
        gdk::Key::Z => Some(Keycode::Z),
        gdk::Key::a => Some(Keycode::A),
        gdk::Key::b => Some(Keycode::B),
        gdk::Key::c => Some(Keycode::C),
        gdk::Key::d => Some(Keycode::D),
        gdk::Key::e => Some(Keycode::E),
        gdk::Key::f => Some(Keycode::F),
        gdk::Key::g => Some(Keycode::G),
        gdk::Key::h => Some(Keycode::H),
        gdk::Key::i => Some(Keycode::I),
        gdk::Key::j => Some(Keycode::J),
        gdk::Key::k => Some(Keycode::K),
        gdk::Key::l => Some(Keycode::L),
        gdk::Key::m => Some(Keycode::M),
        gdk::Key::n => Some(Keycode::N),
        gdk::Key::o => Some(Keycode::O),
        gdk::Key::p => Some(Keycode::P),
        gdk::Key::q => Some(Keycode::Q),
        gdk::Key::r => Some(Keycode::R),
        gdk::Key::s => Some(Keycode::S),
        gdk::Key::t => Some(Keycode::T),
        gdk::Key::u => Some(Keycode::U),
        gdk::Key::v => Some(Keycode::V),
        gdk::Key::w => Some(Keycode::W),
        gdk::Key::x => Some(Keycode::X),
        gdk::Key::y => Some(Keycode::Y),
        gdk::Key::z => Some(Keycode::Z),
        gdk::Key::Delete => Some(Keycode::DELETE),
        gdk::Key::Caps_Lock => Some(Keycode::CAPSLOCK),
        gdk::Key::F1 => Some(Keycode::F1),
        gdk::Key::F2 => Some(Keycode::F2),
        gdk::Key::F3 => Some(Keycode::F3),
        gdk::Key::F4 => Some(Keycode::F4),
        gdk::Key::F5 => Some(Keycode::F5),
        gdk::Key::F6 => Some(Keycode::F6),
        gdk::Key::F7 => Some(Keycode::F7),
        gdk::Key::F8 => Some(Keycode::F8),
        gdk::Key::F9 => Some(Keycode::F9),
        gdk::Key::F10 => Some(Keycode::F10),
        gdk::Key::F11 => Some(Keycode::F11),
        gdk::Key::F12 => Some(Keycode::F12),
        gdk::Key::Print => Some(Keycode::PRINTSCREEN),
        gdk::Key::Scroll_Lock => Some(Keycode::SCROLLLOCK),
        gdk::Key::Pause => Some(Keycode::PAUSE),
        gdk::Key::Insert => Some(Keycode::INSERT),
        gdk::Key::Home => Some(Keycode::HOME),
        gdk::Key::Page_Up => Some(Keycode::PAGEUP),
        gdk::Key::End => Some(Keycode::END),
        gdk::Key::Page_Down => Some(Keycode::PAGEDOWN),
        gdk::Key::Right => Some(Keycode::RIGHT),
        gdk::Key::Left => Some(Keycode::LEFT),
        gdk::Key::Down => Some(Keycode::DOWN),
        gdk::Key::Up => Some(Keycode::UP),
        gdk::Key::Clear => Some(Keycode::NUMLOCKCLEAR),
        gdk::Key::KP_Divide => Some(Keycode::KP_DIVIDE),
        gdk::Key::KP_Multiply => Some(Keycode::KP_MULTIPLY),
        gdk::Key::KP_Subtract => Some(Keycode::KP_MINUS),
        gdk::Key::KP_Add => Some(Keycode::KP_PLUS),
        gdk::Key::KP_Enter => Some(Keycode::KP_ENTER),
        gdk::Key::KP_1 => Some(Keycode::KP_1),
        gdk::Key::KP_2 => Some(Keycode::KP_2),
        gdk::Key::KP_3 => Some(Keycode::KP_3),
        gdk::Key::KP_4 => Some(Keycode::KP_4),
        gdk::Key::KP_5 => Some(Keycode::KP_5),
        gdk::Key::KP_6 => Some(Keycode::KP_6),
        gdk::Key::KP_7 => Some(Keycode::KP_7),
        gdk::Key::KP_8 => Some(Keycode::KP_8),
        gdk::Key::KP_9 => Some(Keycode::KP_9),
        gdk::Key::KP_0 => Some(Keycode::KP_0),
        gdk::Key::KP_Decimal => Some(Keycode::KP_PERIOD),
        gdk::Key::ApplicationLeft => Some(Keycode::APPLICATION),
        gdk::Key::PowerOff => Some(Keycode::POWER),
        gdk::Key::KP_Equal => Some(Keycode::KP_EQUALS),
        gdk::Key::F13 => Some(Keycode::F13),
        gdk::Key::F14 => Some(Keycode::F14),
        gdk::Key::F15 => Some(Keycode::F15),
        gdk::Key::F16 => Some(Keycode::F16),
        gdk::Key::F17 => Some(Keycode::F17),
        gdk::Key::F18 => Some(Keycode::F18),
        gdk::Key::F19 => Some(Keycode::F19),
        gdk::Key::F20 => Some(Keycode::F20),
        gdk::Key::F21 => Some(Keycode::F21),
        gdk::Key::F22 => Some(Keycode::F22),
        gdk::Key::F23 => Some(Keycode::F23),
        gdk::Key::F24 => Some(Keycode::F24),
        gdk::Key::Execute => Some(Keycode::EXECUTE),
        gdk::Key::Help => Some(Keycode::HELP),
        gdk::Key::Menu => Some(Keycode::MENU),
        gdk::Key::Select => Some(Keycode::SELECT),
        gdk::Key::Stop => Some(Keycode::STOP),
        gdk::Key::Redo => Some(Keycode::AGAIN),
        gdk::Key::Undo => Some(Keycode::UNDO),
        gdk::Key::Cut => Some(Keycode::CUT),
        gdk::Key::Copy => Some(Keycode::COPY),
        gdk::Key::Paste => Some(Keycode::PASTE),
        gdk::Key::Find => Some(Keycode::FIND),
        gdk::Key::AudioMute => Some(Keycode::MUTE),
        gdk::Key::AudioRaiseVolume => Some(Keycode::VOLUMEUP),
        gdk::Key::AudioLowerVolume => Some(Keycode::VOLUMEDOWN),
        gdk::Key::KP_Separator => Some(Keycode::KP_COMMA),
        gdk::Key::Sys_Req => Some(Keycode::SYSREQ),
        gdk::Key::Cancel => Some(Keycode::CANCEL),
        gdk::Key::_3270_CursorSelect => Some(Keycode::CRSEL),
        gdk::Key::_3270_ExSelect => Some(Keycode::EXSEL),
        gdk::Key::currency => Some(Keycode::CURRENCYUNIT),
        gdk::Key::cent => Some(Keycode::CURRENCYSUBUNIT),
        gdk::Key::KP_Tab => Some(Keycode::KP_TAB),
        gdk::Key::KP_Delete => Some(Keycode::KP_BACKSPACE),
        gdk::Key::KP_Space => Some(Keycode::KP_SPACE),
        gdk::Key::plusminus => Some(Keycode::KP_PLUSMINUS),
        gdk::Key::Control_L => Some(Keycode::LCTRL),
        gdk::Key::Shift_L => Some(Keycode::LSHIFT),
        gdk::Key::Alt_L => Some(Keycode::LALT),
        gdk::Key::Super_L => Some(Keycode::LGUI),
        gdk::Key::Control_R => Some(Keycode::RCTRL),
        gdk::Key::Shift_R => Some(Keycode::RSHIFT),
        gdk::Key::Alt_R => Some(Keycode::RALT),
        gdk::Key::Super_R => Some(Keycode::RGUI),
        gdk::Key::Mode_switch => Some(Keycode::MODE),
        gdk::Key::AudioNext => Some(Keycode::AUDIONEXT),
        gdk::Key::AudioPrev => Some(Keycode::AUDIOPREV),
        gdk::Key::AudioStop => Some(Keycode::AUDIOSTOP),
        gdk::Key::AudioPlay => Some(Keycode::AUDIOPLAY),
        gdk::Key::WWW => Some(Keycode::WWW),
        gdk::Key::Mail => Some(Keycode::MAIL),
        gdk::Key::Calculator => Some(Keycode::CALCULATOR),
        gdk::Key::MyComputer => Some(Keycode::COMPUTER),
        gdk::Key::MonBrightnessDown => Some(Keycode::BRIGHTNESSDOWN),
        gdk::Key::MonBrightnessUp => Some(Keycode::BRIGHTNESSUP),
        gdk::Key::Display => Some(Keycode::DISPLAYSWITCH),
        gdk::Key::KbdLightOnOff => Some(Keycode::KBDILLUMTOGGLE),
        gdk::Key::KbdBrightnessDown => Some(Keycode::KBDILLUMDOWN),
        gdk::Key::KbdBrightnessUp => Some(Keycode::KBDILLUMUP),
        gdk::Key::Eject => Some(Keycode::EJECT),
        gdk::Key::Sleep => Some(Keycode::SLEEP),
        _ => None,
    }
}

pub fn into_sdl_modifiers(gdk_mod: gdk::ModifierType) -> Mod {
    let mut sdl_mod = Mod::empty();
    macro_rules! map_bit {
        ($src_bit:expr, $dst_bit:expr) => {
            if gdk_mod.contains($src_bit) {
                sdl_mod |= $dst_bit;
            }
        };
    }

    map_bit!(gdk::ModifierType::CONTROL_MASK, Mod::LCTRLMOD);
    map_bit!(gdk::ModifierType::ALT_MASK, Mod::LALTMOD);
    map_bit!(gdk::ModifierType::SHIFT_MASK, Mod::LSHIFTMOD);
    map_bit!(gdk::ModifierType::SUPER_MASK, Mod::LGUIMOD);

    sdl_mod
}

/*

*/
