[package]
name = "m64prs-native"
version = "0.1.0"
edition = "2021"

build = "build/main.rs"

[dependencies]

[build-dependencies]
os_pipe = { workspace = true }
walkdir = { workspace = true }
which = { workspace = true }
