[package]
name = "m64prs-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dlopen2 = "0.6.1"
once_cell = "1.19.0"

[build-dependencies]
reqwest = { version = "0.11.23", features = ["blocking"] }
zip = "0.6.6"
bindgen = "0.69.2"
regex = "1.10.3"