[package]
name = "m64prs-gtk-utils"
version = "0.1.0"
edition = "2021"

[dependencies]

m64prs-gtk-macros = { workspace = true }

glib = { workspace = true }
gio = { workspace = true }
gtk = { workspace = true }

futures = { workspace = true }