[package]
name = "m64prs-gtk-test"
version = "0.1.0"
edition = "2021"

[dependencies]
gtk = { version = "0.9.3", package = "gtk4", features = ["v4_14"] }
send_wrapper = "0.6.0"

[target.'cfg(target_os = "linux")'.dependencies]
gdk_wayland = { version = "0.9.3", package = "gdk4-wayland" }
gdk_x11 = { version = "0.9.3", package = "gdk4-x11" }
